package com.appdev.notetect.backend.entity;

import javax.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Note {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    // The text generated by AI from uploaded files
    @Column(columnDefinition = "TEXT")
    private String content;

    // The original filename (pdf, docx, etc.)
    private String filename;

    // Timestamp for creation
    private String createdAt;

    // The folder this note belongs to
    @ManyToOne
    @JoinColumn(name = "folder_id")
    private Folder folder;

    // The subject assigned by the user (can be anything)
    @ManyToOne
    @JoinColumn(name = "subject_id")
    private Subject subject;
}
