package com.appdevg4.krazyrapidboots.notetect.entity;

import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import lombok.AllArgsConstructor;
import jakarta.persistence.Column;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Entity;
import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Note {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    // The text generated by AI from uploaded files
    @Column(columnDefinition = "TEXT")
    private String content;

    // The topic/title of the note
    private String title;

    // The original filename (pdf, docx, etc.)
    private String filename;

    // Timestamp for creation
    private String createdAt;

    // The user who owns this note
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    @JsonIgnore
    private User user;

    // The folder this note belongs to
    @ManyToOne
    @JoinColumn(name = "folder_id")
    private Folder folder;

    // The subject assigned by the user (can be anything)
    @ManyToOne
    @JoinColumn(name = "subject_id")
    private Subject subject;
}
