package com.appdevg4.krazyrapidboots.notetect.entity;

import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Column;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Entity;
import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity
public class Note {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    // The text generated by AI from uploaded files
    @Column(columnDefinition = "TEXT")
    private String content;

    // The topic/title of the note
    private String title;

    // The original filename (pdf, docx, etc.)
    private String filename;

    // Timestamp for creation
    private String createdAt;

    // The user who owns this note
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    @JsonIgnore
    private User user;

    // The folder this note belongs to (User → Subject → Folder → Note hierarchy)
    @ManyToOne
    @JoinColumn(name = "folder_id")
    private Folder folder;

    // Constructors
    public Note() {}

    public Note(int id, String content, String title, String filename, String createdAt, User user, Folder folder) {
        this.id = id;
        this.content = content;
        this.title = title;
        this.filename = filename;
        this.createdAt = createdAt;
        this.user = user;
        this.folder = folder;
    }

    // Getters and Setters
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getContent() { return content; }
    public void setContent(String content) { this.content = content; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getFilename() { return filename; }
    public void setFilename(String filename) { this.filename = filename; }

    public String getCreatedAt() { return createdAt; }
    public void setCreatedAt(String createdAt) { this.createdAt = createdAt; }

    public User getUser() { return user; }
    public void setUser(User user) { this.user = user; }

    public Folder getFolder() { return folder; }
    public void setFolder(Folder folder) { this.folder = folder; }
}
